"""One-off Markdown -> .docx converter for the FYP report draft.

Not a general-purpose converter — handles exactly the markdown subset
used in FYP_Report.md: #/##/### headings, pipe tables, bold/italic/code
inline spans, bullet and numbered lists, blockquote-style italic notes,
and horizontal rules (rendered as a page break between major chapters).
"""
import datetime as _dt
import re
import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "FYP_Report.md"
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else SRC.with_suffix(".docx")

INLINE_RE = re.compile(r"(\*\*.+?\*\*|\*.+?\*|`.+?`)")


def add_inline_runs(paragraph, text, bold=False, italic=False):
    """Recursive so nested spans keep both formats: a `code` span inside a
    **bold** run used to be emitted with its literal backticks, because the
    outer match consumed the whole chunk and never re-scanned it."""
    for chunk in INLINE_RE.split(text):
        if not chunk:
            continue
        if chunk.startswith("**") and chunk.endswith("**"):
            add_inline_runs(paragraph, chunk[2:-2], bold=True, italic=italic)
        elif chunk.startswith("*") and chunk.endswith("*") and not chunk.startswith("**"):
            add_inline_runs(paragraph, chunk[1:-1], bold=bold, italic=True)
        elif chunk.startswith("`") and chunk.endswith("`"):
            run = paragraph.add_run(chunk[1:-1])
            run.font.name = "Consolas"
            run.font.size = Pt(10)
            run.bold, run.italic = bold, italic
        else:
            run = paragraph.add_run(chunk)
            run.bold, run.italic = bold, italic


def set_cell_shading(cell, color_hex):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), color_hex)
    tcPr.append(shd)


# Word field codes. A field is four runs: begin / instruction / separate /
# cached-result / end. Word replaces the cached result when the field is
# updated; `enable_field_autoupdate` below makes that happen on open.
FIELD_INSTRUCTIONS = {
    "TOC": r'TOC \o "1-3" \h \z \u',
    # \c "Figure" would collect paragraphs containing a SEQ Figure
    # field; these captions carry literal, chapter-scoped numbers instead
    # ("Figure 4.1 — ..."), so \c finds nothing and Word renders "No
    # table of figures entries found". \t collects by paragraph style,
    # which is why figure and table captions use two distinct styles.
    "LOF": r'TOC \h \z \t "Caption,1"',
    "LOT": r'TOC \h \z \t "Table Caption,1"',
}

FIELD_PLACEHOLDER = (
    "[This list is generated by Word. If it is still showing this line, "
    "press Ctrl+A then F9 to update all fields.]"
)


def add_field(paragraph, instruction, placeholder=""):
    begin = paragraph.add_run()
    fld = OxmlElement("w:fldChar")
    fld.set(qn("w:fldCharType"), "begin")
    fld.set(qn("w:dirty"), "true")
    begin._r.append(fld)

    instr_run = paragraph.add_run()
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = " " + instruction + " "
    instr_run._r.append(instr)

    sep = paragraph.add_run()
    fld = OxmlElement("w:fldChar")
    fld.set(qn("w:fldCharType"), "separate")
    sep._r.append(fld)

    if placeholder:
        run = paragraph.add_run(placeholder)
        run.italic = True
        run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    end = paragraph.add_run()
    fld = OxmlElement("w:fldChar")
    fld.set(qn("w:fldCharType"), "end")
    end._r.append(fld)


# w:updateFields must sit in its schema-defined position inside settings.xml
# (after w:alwaysMergeEmptyNamespace, before w:hdrShapeDefaults/w:compat), or
# Word reports the document as containing unreadable content.
_SETTINGS_SUCCESSORS = (
    "w:hdrShapeDefaults", "w:footnotePr", "w:endnotePr", "w:compat",
    "w:docVars", "w:rsids", "w:attachedSchema", "w:themeFontLang",
)


def enable_field_autoupdate(doc):
    settings = doc.settings.element
    if settings.find(qn("w:updateFields")) is not None:
        return
    node = OxmlElement("w:updateFields")
    node.set(qn("w:val"), "true")
    for tag in _SETTINGS_SUCCESSORS:
        anchor = settings.find(qn(tag))
        if anchor is not None:
            anchor.addprevious(node)
            return
    settings.append(node)


def add_page_numbers(doc):
    """Centred 'Page N' footer on every section — required by the report
    template and needed for the generated tables of contents to be usable."""
    for section in doc.sections:
        footer = section.footer
        footer.is_linked_to_previous = False
        para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        para.text = ""
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run("Page ")
        run.font.size = Pt(9)
        add_field(para, "PAGE")
        run = para.add_run(" of ")
        run.font.size = Pt(9)
        add_field(para, "NUMPAGES")
        for r in para.runs:
            r.font.size = Pt(9)
            r.font.color.rgb = RGBColor(0x60, 0x60, 0x60)


TABLE_CAPTION_STYLE = "Table Caption"


def ensure_table_caption_style(doc):
    """A clone of Caption, used only for table captions, so the List of
    Tables and the List of Figures can each collect one style."""
    if TABLE_CAPTION_STYLE in [s.name for s in doc.styles]:
        return
    style = doc.styles.add_style(TABLE_CAPTION_STYLE, WD_STYLE_TYPE.PARAGRAPH)
    style.base_style = doc.styles["Caption"]


# The deliverable's own File -> Info -> Properties. python-docx's default
# template ships dc:creator "python-docx", dc:description "generated by
# python-docx" and a 2013 creation date — all visible in Word and read by
# Turnitin's metadata view, which is a bad look on a document carrying a
# Declaration of AI Use.
AUTHOR = "Ibtissam Merzouqi"
TITLE = ("Privacy-Preserving Cognitive Engagement Detection from Webcam Video "
         "Using an Edge-Deployed Temporal Convolutional Network")
SUBJECT = "MSc Data Science dissertation, University of Greenwich"


def set_core_properties(doc):
    cp = doc.core_properties
    cp.author = AUTHOR
    cp.last_modified_by = AUTHOR
    cp.title = TITLE
    cp.subject = SUBJECT
    cp.comments = ""
    cp.category = ""
    cp.keywords = ("engagement detection; edge machine learning; in-browser "
                   "inference; temporal convolutional network; DAiSEE; "
                   "privacy-preserving computer vision")
    now = _dt.datetime.now()
    cp.created = now
    cp.modified = now
    cp.revision = 1



def restart_numbering(doc, paragraph):
    """Clone the List Number abstract numbering into a fresh w:num so this
    list starts at 1 instead of continuing the previous one."""
    numbering = doc.part.numbering_part.element
    style = doc.styles["List Number"]
    abstract_id = None
    pr = style.element.find(qn("w:pPr"))
    if pr is not None:
        numpr = pr.find(qn("w:numPr"))
        if numpr is not None:
            numid = numpr.find(qn("w:numId"))
            if numid is not None:
                src = numid_val = numid.get(qn("w:val"))
                for num in numbering.findall(qn("w:num")):
                    if num.get(qn("w:numId")) == src:
                        a = num.find(qn("w:abstractNumId"))
                        if a is not None:
                            abstract_id = a.get(qn("w:val"))
    if abstract_id is None:
        return
    used = [int(n.get(qn("w:numId"))) for n in numbering.findall(qn("w:num"))]
    new_id = str(max(used) + 1 if used else 1)
    num = OxmlElement("w:num")
    num.set(qn("w:numId"), new_id)
    a = OxmlElement("w:abstractNumId")
    a.set(qn("w:val"), abstract_id)
    num.append(a)
    override = OxmlElement("w:lvlOverride")
    override.set(qn("w:ilvl"), "0")
    start = OxmlElement("w:startOverride")
    start.set(qn("w:val"), "1")
    override.append(start)
    num.append(override)
    numbering.append(num)

    ppr = paragraph._p.get_or_add_pPr()
    numpr = ppr.find(qn("w:numPr"))
    if numpr is None:
        numpr = OxmlElement("w:numPr")
        ppr.append(numpr)
    for tag in ("w:ilvl", "w:numId"):
        old_el = numpr.find(qn(tag))
        if old_el is not None:
            numpr.remove(old_el)
    ilvl = OxmlElement("w:ilvl"); ilvl.set(qn("w:val"), "0")
    nid = OxmlElement("w:numId"); nid.set(qn("w:val"), new_id)
    numpr.append(ilvl); numpr.append(nid)


def parse_table(lines, i):
    rows = []
    while i < len(lines) and lines[i].strip().startswith("|"):
        row = [c.strip() for c in lines[i].strip().strip("|").split("|")]
        rows.append(row)
        i += 1
    # drop the "---|---" separator row (row index 1)
    if len(rows) > 1 and all(set(c) <= set("-: ") for c in rows[1]):
        rows.pop(1)
    return rows, i


def build(doc, lines):
    i = 0
    n = len(lines)
    first_h1 = True
    in_front_matter = True
    prev_was_numbered = False
    while i < n:
        line = lines[i]
        stripped = line.strip()

        if stripped == "":
            i += 1
            continue

        if stripped == "---":
            # page break between major sections, skip on very first lines
            if doc.paragraphs:
                doc.add_page_break()
            in_front_matter = False
            i += 1
            continue

        # Word field marker: <!--WORD-FIELD:TOC|LOF|LOT-->
        fm = re.match(r"^<!--WORD-FIELD:(\w+)-->$", stripped)
        if fm:
            key = fm.group(1)
            if key in FIELD_INSTRUCTIONS:
                p = doc.add_paragraph()
                add_field(p, FIELD_INSTRUCTIONS[key], FIELD_PLACEHOLDER)
            i += 1
            continue

        if stripped.startswith("<!--") and stripped.endswith("-->"):
            i += 1
            continue

        if stripped.startswith("| "):
            rows, i = parse_table(lines, i)
            if rows:
                table = doc.add_table(rows=len(rows), cols=len(rows[0]))
                table.style = "Light Grid Accent 1"
                table.alignment = WD_TABLE_ALIGNMENT.CENTER
                for r, row in enumerate(rows):
                    for c, cell_text in enumerate(row):
                        if c >= len(table.columns):
                            continue
                        cell = table.cell(r, c)
                        cell.text = ""
                        p = cell.paragraphs[0]
                        add_inline_runs(p, cell_text)
                        if r == 0:
                            for run in p.runs:
                                run.bold = True
                            set_cell_shading(cell, "D9E2F3")
                doc.add_paragraph("")
            continue

        # image: ![caption](path) — path relative to the REPO ROOT, embedded
        # at up to 6.2in width with the caption as a small centred line below.
        img = re.match(r"^!\[(.*)\]\((.+)\)$", stripped)
        if img:
            caption, rel_path = img.group(1), img.group(2)
            # Paths are relative to the .md (so the report also renders
            # correctly on GitHub, which Appendix G points the examiner to).
            img_path = (SRC.parent / rel_path).resolve()
            if img_path.exists():
                p = doc.add_paragraph()
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                p.add_run().add_picture(str(img_path), width=Inches(6.2))
                if caption:
                    # Real Word "Caption" style so References -> Insert
                    # Table of Figures picks every figure up automatically.
                    cp = doc.add_paragraph(style="Caption")
                    cp.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    run = cp.add_run(caption)
                    run.font.size = Pt(9)
            else:
                doc.add_paragraph(f"[missing image: {rel_path}]")
            i += 1
            continue

        m = re.match(r"^(#{1,3})\s+(.*)$", stripped)
        if m:
            level = len(m.group(1))
            text = m.group(2).strip()
            # A Table of Contents that lists itself (and the two lists that
            # sit beside it) reads as a mistake. Render these three as
            # heading-looking paragraphs with no Heading style, so the
            # `TOC \o "1-3"` field cannot pick them up.
            if text in ("Table of Contents", "List of Figures", "List of Tables"):
                p = doc.add_paragraph()
                run = p.add_run(text)
                run.bold = True
                run.font.size = Pt(13)
                run.font.color.rgb = RGBColor(0x1F, 0x38, 0x64)
                i += 1
                continue
            if level == 1:
                if first_h1:
                    p = doc.add_paragraph()
                    run = p.add_run(text)
                    run.bold = True
                    run.font.size = Pt(20)
                    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    first_h1 = False
                else:
                    doc.add_heading(text, level=1)
            elif level == 2:
                doc.add_heading(text, level=2)
            else:
                doc.add_heading(text, level=3)
            i += 1
            continue

        prev_was_numbered = False

        # bullet list
        if stripped.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            add_inline_runs(p, stripped[2:])
            i += 1
            continue

        # numbered list
        m = re.match(r"^(\d+)\.\s+(.*)$", stripped)
        if m:
            p = doc.add_paragraph(style="List Number")
            # Every "List Number" paragraph shares one numbering sequence, so
            # the document's later numbered lists continued the earlier ones
            # (Future Work rendered as 4.-9. instead of 1.-6.). Give each new
            # run its own numId so it restarts at 1.
            if not prev_was_numbered:
                restart_numbering(doc, p)
            add_inline_runs(p, m.group(2))
            prev_was_numbered = True
            i += 1
            continue

        # Cover-page lines: bold-only, and ONLY before the first rule. The
        # old `count("**") == 2` test both missed the supervisor/second-marker
        # line (which has two bold spans, so it stayed left-aligned amid a
        # centred cover) and centred bold lead-ins in body prose.
        if in_front_matter and stripped.startswith("**") and stripped.endswith("**"):
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            add_inline_runs(p, stripped)
            i += 1
            continue

        # italic-only note/placeholder paragraph
        if stripped.startswith("*") and stripped.endswith("*") and not stripped.startswith("**"):
            # Inline spans still have to be parsed inside the italic note,
            # or `code` renders with its literal backticks (visible on the
            # title page's provenance paragraph).
            p = doc.add_paragraph()
            add_inline_runs(p, stripped[1:-1])
            for run in p.runs:
                run.italic = True
                run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)
            i += 1
            continue

        # table caption line ("Table 4.1 — ...") -> Word Caption style so
        # Insert Table of Figures / Tables finds it; prose mentions like
        # "Table 4.1 shows..." lack the em-dash and stay normal paragraphs.
        if re.match(r"^Table \d+\.\d+ —", stripped):
            p = doc.add_paragraph(style=TABLE_CAPTION_STYLE)
            add_inline_runs(p, stripped)
            i += 1
            continue

        # normal paragraph
        p = doc.add_paragraph()
        add_inline_runs(p, stripped)
        p.paragraph_format.space_after = Pt(8)
        i += 1


def main():
    text = SRC.read_text(encoding="utf-8")
    lines = text.split("\n")

    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    for lvl, size in ((1, 16), (2, 13), (3, 12)):
        hstyle = doc.styles[f"Heading {lvl}"]
        hstyle.font.size = Pt(size)
        hstyle.font.color.rgb = RGBColor(0x1F, 0x38, 0x64)
        hstyle.font.bold = True

    ensure_table_caption_style(doc)
    build(doc, lines)
    add_page_numbers(doc)
    set_core_properties(doc)
    enable_field_autoupdate(doc)
    doc.save(str(OUT))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
